// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBachx5XgArg6JHL1WF947GUr6ffq9eRo8',
    appId: '1:675961039544:web:9ff41bdf7e5282b528224d',
    messagingSenderId: '675961039544',
    projectId: 'the-big-gym-218ee',
    authDomain: 'the-big-gym-218ee.firebaseapp.com',
    storageBucket: 'the-big-gym-218ee.firebasestorage.app',
    measurementId: 'G-8Z4D15P9X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEDUN_UNea_JWzzH2rBREdRDcjp_W-OZk',
    appId: '1:675961039544:android:9f50ee8cdb9921b528224d',
    messagingSenderId: '675961039544',
    projectId: 'the-big-gym-218ee',
    storageBucket: 'the-big-gym-218ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOX6s1QdY0EZIvDPRvadib11Ga2tMz7XA',
    appId: '1:675961039544:ios:86552b89ec6f910328224d',
    messagingSenderId: '675961039544',
    projectId: 'the-big-gym-218ee',
    storageBucket: 'the-big-gym-218ee.firebasestorage.app',
    iosClientId: '675961039544-m9v78s4g4l7u6acsff283vkig6tjh97p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymRat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOX6s1QdY0EZIvDPRvadib11Ga2tMz7XA',
    appId: '1:675961039544:ios:86552b89ec6f910328224d',
    messagingSenderId: '675961039544',
    projectId: 'the-big-gym-218ee',
    storageBucket: 'the-big-gym-218ee.firebasestorage.app',
    iosClientId: '675961039544-m9v78s4g4l7u6acsff283vkig6tjh97p.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymRat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBachx5XgArg6JHL1WF947GUr6ffq9eRo8',
    appId: '1:675961039544:web:eacbb68ee944c2f628224d',
    messagingSenderId: '675961039544',
    projectId: 'the-big-gym-218ee',
    authDomain: 'the-big-gym-218ee.firebaseapp.com',
    storageBucket: 'the-big-gym-218ee.firebasestorage.app',
    measurementId: 'G-QT4HVE4H5K',
  );
}
